#!/usr/bin/env python3
import re

title = input("Enter a movie title: ")
year = input("Enter the year of release: ")

string = f"Some text {title} ({year})"

pattern = r'\b[a-zA-Z\s}+ \(\d{4}\)\b'
matches = re.findall(pattern, string)

for match in matches:
 print(match)
